name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile MikoOS CLI
      run: |
        g++ src/main.cpp -o miko -static

    - name: Test Binary
      run: |
        chmod +x miko
        ./miko --help || true

    -  name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: miko-binary
        path: miko
name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/miko
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
